/**
 * Generates src/theme/tokens.generated.css (Tailwind v4 @theme) from src/tokens/tokens.ts.
 * Run: node scripts/build-tokens.ts   (Node >= 22.18 strips TS types natively)
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { tokens } from '../src/tokens/tokens.ts';

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

const lines: string[] = [];
const push = (name: string, value: string | number) => lines.push(`  --${name}: ${value};`);

lines.push('  /* Color scales */');
for (const [scale, steps] of Object.entries(tokens.scales)) {
  for (const [step, value] of Object.entries(steps)) {
    push(`color-${kebab(scale)}-${step}`, value);
  }
}

lines.push('  /* Role colors */');
for (const [role, value] of Object.entries(tokens.colors)) {
  push(`color-${kebab(role)}`, value);
}

lines.push('  /* Typography */');
push('font-sans', tokens.typography.fontFamily.sans);
push('font-serif', tokens.typography.fontFamily.serif);
push('text-xs', '0.75rem');
push('text-xs--line-height', '1rem');

lines.push('  /* Radius */');
for (const [name, value] of Object.entries(tokens.radius)) {
  if (name === 'none' || name === 'full') continue;
  push(`radius-${name}`, value);
}

lines.push('  /* Shadows */');
for (const [name, value] of Object.entries(tokens.shadows)) {
  push(`shadow-${kebab(name)}`, value);
}

lines.push('  /* Breakpoints */');
for (const [name, value] of Object.entries(tokens.breakpoints)) {
  if (value === 0) continue;
  push(`breakpoint-${name}`, `${value / 16}rem`);
}

const zIndex = Object.entries(tokens.zIndex)
  .map(([name, value]) => `  --z-${kebab(name)}: ${value};`)
  .join('\n');

const css = `/* AUTO-GENERATED by scripts/build-tokens.ts from src/tokens/tokens.ts. Do not edit. */
@theme {
${lines.join('\n')}
}

:root {
  --top-nav-height: ${tokens.layout.topNavHeight}px;
  --input-height: ${tokens.layout.inputHeight}px;
${zIndex}
}
`;

const out = fileURLToPath(new URL('../src/theme/tokens.generated.css', import.meta.url));
writeFileSync(out, css);
console.log(`Wrote ${out}`);
